import type {TProductColumn, TProductSearchParams} from "@/types/product.types";

export const DEFAULT_PRODUCT_SEARCH_PARAMS: TProductSearchParams = {
  pageNumber: 1,
  pageSize: 10,
  q: "",
  vendor: "",
  minPrice: null,
  maxPrice: null,
  availability: "all"
};

export const PRODUCT_COLUMNS: TProductColumn[] = [
  //   "_AIRBYTE_RAW_ID",
  //   "_AIRBYTE_EXTRACTED_AT",
  //   "_AIRBYTE_META",
  //   "_AIRBYTE_GENERATION_ID",
  "ID",
  //   "SEO",
  //   "TAGS",
  //   "IMAGE",
  "TITLE",
  //   "HANDLE",
  //   "IMAGES",
  //   "STATUS",
  "VENDOR",
  //   "OPTIONS",
  //   "FEEDBACK",
  //   "SHOP_URL",
  //   "VARIANTS",
  //   "BODY_HTML",
  //   "CREATED_AT",
  //   "DELETED_AT",
  //   "UPDATED_AT",
  "DESCRIPTION"
  //   "MEDIA_COUNT",
  //   "IS_GIFT_CARD",
  //   "PRODUCT_TYPE",
  //   "PUBLISHED_AT",
  //   "FEATURED_IMAGE",
  //   "FEATURED_MEDIA",
  //   "PRICE_RANGE_V2",
  //   "TOTAL_VARIANTS",
  //   "DELETED_MESSAGE",
  //   "PUBLISHED_SCOPE",
  //   "TEMPLATE_SUFFIX",
  //   "TOTAL_INVENTORY",
  //   "DESCRIPTION_HTML",
  //   "ONLINE_STORE_URL",
  //   "TRACKS_INVENTORY",
  //   "LEGACY_RESOURCE_ID",
  //   "DELETED_DESCRIPTION",
  //   "ADMIN_GRAPHQL_API_ID",
  //   "REQUIRES_SELLIN_PLAN",
  //   "HAS_ONLY_DEFAULT_VARIANT",
  //   "ONLINE_STORE_PREVIEW_URL",
  //   "HAS_OUT_OF_STOCK_VARIANTS",
  //   "PRICE_RANGE",
  //   "METAFIELDS"
];
